import "./globals.css";
import Bubbles_Curser from "./components/Bubbles_Curser";
import { Orbitron } from "next/font/google";

export const metadata = {
  title: "MJ",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orbitron.className}>
      <body>
        {children}
        <Bubbles_Curser /> {/* Client component */}
      </body>
    </html>
  );
}
